dependencies {
    testImplementation platform(libs.junit.bom)
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

tasks.named('downloadSource') {

}

tasks.named('buildNative') {
    additionalCFiles = downloadSource.srcDir.files("lib/src/lib.c")
    additionalIncludeDirs = [downloadSource.srcDir.dir("lib/src")]
}